[server]
heartbeat_interval_ms = 1000

[batch]

[streaming]
checkpoint_interval_ms = 250
in_flight_barrier_nums = 40
worker_node_parallelism = 4

[storage]
shared_buffer_capacity_mb = 4096
sstable_size_mb = 256
block_size_kb = 1024
bloom_false_positive = 0.01
data_directory = "hummock_001"
block_cache_capacity_mb = 4096
meta_cache_capacity_mb = 1024
compactor_memory_limit_mb = 8096

[storage.file_cache]
capacity = 1073741824                 # 1 GiB
total_buffer_capacity = 134217728     # 128 MiB
cache_file_fallocate_unit = 100663296 # 96 MiB
