[package]
name = "risingwave_hummock_test"
version = "0.1.10"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { version = "1" }
fail = "0.5"
futures = { version = "0.3" }
itertools = "0.10"
madsim = "=0.2.0-alpha.5"
parking_lot = "0.12"
rand = "0.8"
risingwave_common = { path = "../../common" }
risingwave_hummock_sdk = { path = "../hummock_sdk" }
risingwave_meta = { path = "../../meta", features = ["test"] }
risingwave_object_store = { path = "../../object_store" }
risingwave_pb = { path = "../../prost" }
risingwave_rpc_client = { path = "../../rpc_client" }
risingwave_storage = { path = "..", features = ["test"] }
tokio = { version = "=0.2.0-alpha.5", package = "madsim-tokio" }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[features]
failpoints = ["risingwave_storage/failpoints"]
