version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rw-build-env:
    image: public.ecr.aws/x5u3w5h6/rw-build-env:v20220729
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ..:/risingwave

  regress-test-env:
    image: public.ecr.aws/x5u3w5h6/rw-build-env:v20220729
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ..:/risingwave

  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 40s
      retries: 5
    networks:
      nw:
        ipv4_address: 172.24.2.1

networks:
  nw:
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: "172.24.2.0/16"
