[package]
name = "risingwave_common"
version = "0.1.10"
edition = "2021"

[dependencies]
anyhow = "1"
async-stream = "0.3"
async-trait = "0.1"
auto_enums = "0.7"
bitflags = "1.3.2"
byteorder = "1"
bytes = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
comfy-table = "6"
crc32fast = "1"
either = "1"
enum-as-inner = "0.5"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = "0.2"
humantime = "2.1"
itertools = "0.10"
lazy_static = "1"
log = "0.4"
lru = { git = "https://github.com/singularity-data/lru-rs.git", rev = "e0e9ddaf8e4a51c244a03676734437e68a336b30" }
madsim = "=0.2.0-alpha.5"
memcomparable = { path = "../utils/memcomparable" }
more-asserts = "0.3"
num-traits = "0.2"
num_cpus = "1.13.1"
parking_lot = "0.12"
paste = "1"
pgtype-binary = { path = "../utils/pgtype-binary" }
prometheus = { version = "0.13" }
prost = "0.10"
rand = "0.8"
regex = "1"
risingwave_pb = { path = "../prost" }
rust_decimal = "1"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
smallvec = "1"
spin = "0.9"
thiserror = "1"
tokio = { version = "=0.2.0-alpha.5", package = "madsim-tokio", features = ["rt", "rt-multi-thread", "sync", "macros", "time", "signal"] }
tokio-stream = "0.1"
toml = "0.5"
tonic = { version = "=0.2.0-alpha.5", package = "madsim-tonic" }
tracing = { version = "0.1" }
twox-hash = "1"
url = "2"
value-encoding = { path = "../utils/value-encoding" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = { git = "https://github.com/tikv/procinfo-rs", rev = "6599eb9dca74229b2c1fcc44118bef7eff127128" }
procfs = { version = "0.12", default-features = false }
libc = "0.2"

[dev-dependencies]
rand = "0.8"
